# Generated by ChatGPT on 2024-XX-XX
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('address', models.TextField(verbose_name='Address')),
                ('scheduled_for', models.DateTimeField(verbose_name='Scheduled for')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered at')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_order', to='appointments.appointment', verbose_name='Appointment')),
            ],
            options={
                'verbose_name': 'Delivery order',
                'verbose_name_plural': 'Delivery orders',
                'db_table': 'delivery_orders',
                'ordering': ['-scheduled_for'],
            },
        ),
    ]
