# Generated by ChatGPT on 2024-XX-XX
from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Base price')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='vendors.vendor', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'services',
                'ordering': ['name'],
                'unique_together': {('vendor', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['vendor', 'is_active'], name='services_vendor_active'),
        ),
    ]
