# Generated by Django 5.2.7 on 2025-10-05 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("name", models.CharField(max_length=200, verbose_name="Business name")),
                (
                    "vendor_type",
                    models.CharField(
                        choices=[
                            ("doctor", "Doctor"),
                            ("delivery", "Delivery Service"),
                            ("other", "Other"),
                        ],
                        default="doctor",
                        max_length=20,
                        verbose_name="Vendor type",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="Phone")),
                ("address", models.TextField(blank=True, verbose_name="Address")),
                ("is_verified", models.BooleanField(default=False, verbose_name="Verified")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "license_number",
                    models.CharField(blank=True, max_length=100, verbose_name="License number"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor",
                "verbose_name_plural": "Vendors",
                "db_table": "vendors",
                "ordering": ["-created_at"],
            },
        ),
    ]
